name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change file permissions
        run: chmod +x ./gradlew

      - name: Listing files
        run: ls -ltr

      - name: Download Gradle wrapper
        run: ./gradlew wrapper --gradle-version=6.8

      - name: Build with Gradle
        run: |
          ./gradlew :kafka-wikimedia:build

      - name: Copy WIKI module JAR file
        run: cp kafka-wikimedia/build/libs/*.jar ${{github.workspace}}

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{github.workspace}}/*.jar